version: '3.7'

services:
  hub:
   image: selenium/hub
   ports:
     - "4444:4444"
   deploy:
    placement:
      constraints:
        - node.role == manager

  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on: 
      - hub
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
        replicas: 5
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5556" /opt/bin/entry_point.sh'
    ports:
      - "5556:5556"

  firefox:
    image: selenium/node-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on: 
      - hub
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
        replicas: 0
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555" /opt/bin/entry_point.sh'
    ports: 
      - "5555:5555"
